### ISSUE TITLE
Is it possible to have the glow as well?

### ISSUE THREAD

**Issue by vaaski** [diogocezar/hyper-synthwave84#1]
I know the glowing effect takes some custom css to be imported for vscode.
hyper supports custom css natively, that should make it possible right?

I could look into it and do a pr if you like.

**Comment by diogocezar** [comment]
Hey man ;) that's would be amazing! We can try to arrive in close glowing effet. Fell free to do your PR ;)

**Comment by vaaski** [comment]
As promised I've looked into it, and it unfortunately seems like it's not possible.
[Since Hyper v2 it uses xterm.js](https://github.com/zeit/hyper/blob/canary/PLUGINS.md#hyper-v2-breaking-changes), which outputs to a canvas, it's no longer possible to apply CSS styles to the text itself. I've also looked at [xterm.js' theming options](https://xtermjs.org/docs/api/terminal/interfaces/itheme/), but it only supports simple colors, no _text-shadow_-like styles.
I will open an issue at [xterm.js](https://github.com/xtermjs/xterm.js) but I doubt that the use case is relevant enough for them to consider adding something like this. I'll include this image to hopefully convince them:
![image](https://user-images.githubusercontent.com/17879327/57194078-a5b2e480-6f42-11e9-807e-85ea36cebc99.png)

**Comment by diogocezar** [comment]
It's a pity, if i could collaborate in some way, please tell me ;)
